import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-gradient-to-r from-blue-500 to-blue-700 p-4 rounded-lg shadow-lg'
      >
        <h1 className="text-6xl text-center font-bold text-white ">
          Road Report
        </h1>
        {children}
      </body>
    </html>
  );
}
